### ISSUE TITLE
Sql error on head or tails

### ISSUE THREAD

**Issue by Malachiel87** [rodel77/MiniBoardGames#12]
i am using sqlite and i got this error when playing head or tail

[11:53:56] [Server thread/WARN]: [MiniBoardGames] Error on sql update (0): [SQLITE_ERROR] SQL error or missing database (table coinflip has no column named headsWins)

**Comment by rodel77** [comment]
Fixed for next update

**Comment by Malachiel87** [comment]
I think you missed also tailsWins :P
[10:04:05] [Server thread/WARN]: [MiniBoardGames] Error on sql update (0): [SQLITE_ERROR] SQL error or missing database (table coinflip has no column named tailsWins)

**Comment by rodel77** [comment]
I see it, fixed for next update!
